server:
  port: 8080
hazelcast:
  client:
  embedded-cluster:
    enable: true
    name: "Hazelcast-embedded-cluster"
    member:
      name: ${MEMBER_NAME:#{'node1'}}
      address: 0.0.0.0
      port: ${MEMBER_PORT:#{5701}}
    members: ${CLUSTER_MEMBERS:#{null}}

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health"