version: '3'
services:
  node1:
    image: spring-boot-hazelcast:1.0.local
    ports:
      - "8081:8080"
      - "5701:5701"
    environment:
      MEMBER_NAME: "node1"
      CLUSTER_MEMBERS: "172.10.1.102:5701,172.10.1.103:5701"
      $JAVA_ARGS:  "-Xms512m -Xmx512m --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED"
    networks:
      cluster-network:
        ipv4_address: 172.10.1.101
  node2:
    image: spring-boot-hazelcast:1.0.local
    ports:
      - "8082:8080"
      - "5702:5701"
    environment:
      MEMBER_NAME: "node2"
      CLUSTER_MEMBERS: "172.10.1.101:5701,172.10.1.103:5701"
      $JAVA_ARGS:  "-Xms512m -Xmx512m --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED"
    networks:
      cluster-network:
        ipv4_address: 172.10.1.102
  node3:
    image: spring-boot-hazelcast:1.0.local
    ports:
      - "8083:8080"
      - "5703:5701"
    environment:
      MEMBER_NAME: "node3"
      CLUSTER_MEMBERS: "172.10.1.101:5701,172.10.1.102:5701"
      $JAVA_ARGS:  "-Xms512m -Xmx512m --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED"
    networks:
      cluster-network:
        ipv4_address: 172.10.1.103
  management-center:
    image: hazelcast/management-center
    ports:
      - "8080:8080"
    environment:
      MC_ADMIN_USER: admin
      MC_ADMIN_PASSWORD: q1w2e3r4
      MC_DEFAULT_CLUSTER: "Hazelcast-embedded-cluster"
      MC_DEFAULT_CLUSTER_MEMBERS: "172.10.1.101,172.10.1.102,172.10.1.103"
    networks:
      cluster-network:
        ipv4_address: 172.10.1.100
networks:
  cluster-network:
    ipam:
      config:
        - subnet: 172.10.1.0/24
